export enum Subjects {
    PropertyCreated = 'property:created',
    PropertyUpdated = 'property:updated',
    BookingCreated = 'booking:created',
    BookingCanceled = 'booking:canceled',
    BookCreated = 'book:created',
    BookUpdated = 'book:updated',
    OrderCreated = 'order:created',
    OrderCanceled = 'order:canceled',
    UserRegistering = 'user:registering',
    UserRegistered = 'user:registered',
    ExpirationComplete = 'expiration:complete',
    PasswordResetRequest = 'password:reset:request',
    UserImageUploaded = 'user:image:uploaded',
    PlacesImageUploaded = 'places:image:uploaded',
    UserImageDeleted = 'user:image:deleted',
    UserUpdated = 'user:updated',
    PlaceUploaded = 'place:uploaded',
    CategoryCreated = 'category:created',
    InvitationCreated = 'invitation:created',
    InviteLiked = 'invite:liked',
    AcceptedToMeet = 'accepted:to:meet',
    NewPrivateFriendship = 'new:private:friendship',
    NewGroupFriendship = 'new:group:friendship',
    InviteApproved = 'invite:approved',
    InviteDisaproved = 'invite:disapproved'
}

